using System.Text.Json;

namespace CxAgent.Core.Plugins;

/// <summary>
/// Reads the published catalog, and keeps the last good copy so the dialog opens without a network.
/// </summary>
public sealed class CatalogReader
{
    /// <summary>Where the catalog is published — regenerated by the release workflow.</summary>
    public const string PublishedUrl = "https://nickprotop.github.io/cxagent/catalog.json";

    private static readonly HttpClient Shared = new();
    private readonly HttpClient _client;
    private readonly string _cachePath;
    private readonly string _url;

    public CatalogReader(HttpClient? client, string cachePath, string url = PublishedUrl)
    {
        _client = client ?? Shared;
        _cachePath = cachePath;
        _url = url;
    }

    /// <summary>
    /// The catalog, from the network when it can be reached and from the cache when it cannot.
    ///
    /// <para>NEVER THROWS. Every failure — an unreachable host, a 500, a truncated body — becomes an
    /// <see cref="Catalog.Error"/> beside whatever entries were still available. A caller can then
    /// show the installed plugins it did not need the network for, and say why the rest are missing.
    /// </para>
    /// </summary>
    public async Task<Catalog> ReadAsync(CancellationToken ct)
    {
        string? failure = null;

        try
        {
            using var response = await _client.GetAsync(_url, ct).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync(ct).ConfigureAwait(false);
                var parsed = Parse(body);
                if (parsed is not null)
                {
                    // WRITTEN ONLY AFTER IT PARSED. Caching a body that could not be read would
                    // replace a good cache with a bad one, and the next offline open would show
                    // nothing rather than something slightly old.
                    TryWriteCache(body);
                    return new Catalog(parsed);
                }
                failure = "the published catalog could not be read as JSON.";
            }
            else failure = $"the catalog request returned {(int)response.StatusCode}.";
        }
        catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException or IOException)
        {
            failure = ex.Message;
        }

        return FromCache(failure);
    }

    private Catalog FromCache(string? failure)
    {
        try
        {
            if (File.Exists(_cachePath))
            {
                var parsed = Parse(File.ReadAllText(_cachePath));
                if (parsed is not null)
                    return new Catalog(parsed, File.GetLastWriteTimeUtc(_cachePath), failure);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { }

        return new Catalog([], null, failure ?? "no catalog has been read yet.");
    }

    private void TryWriteCache(string body)
    {
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(_cachePath)!);
            File.WriteAllText(_cachePath, body);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // A CACHE IS A COURTESY. Failing to write one must not fail a read that succeeded.
        }
    }

    private static IReadOnlyList<CatalogEntry>? Parse(string json)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (!doc.RootElement.TryGetProperty("plugins", out var plugins)) return null;

            var entries = new List<CatalogEntry>();
            foreach (var p in plugins.EnumerateArray())
            {
                var compat = p.TryGetProperty("compatibility", out var c) ? c : default;
                var source = p.TryGetProperty("source", out var s) ? s : default;
                var requires = p.TryGetProperty("requires", out var r) ? r : default;

                var tools = new List<CatalogTool>();
                if (p.TryGetProperty("tools", out var ts))
                    foreach (var t in ts.EnumerateArray())
                        tools.Add(new CatalogTool(
                            Str(t, "name") ?? "",
                            t.TryGetProperty("gated", out var g) ? g.ToString() : "false"));

                entries.Add(new CatalogEntry(
                    Str(p, "name") ?? "",
                    Str(p, "displayName") ?? Str(p, "name") ?? "",
                    Str(p, "version") ?? "",
                    Str(p, "description") ?? "",
                    Str(p, "publisher") ?? "",
                    Str(p, "license") ?? "",
                    Str(p, "repository") ?? "",
                    Str(p, "category") ?? "",
                    Str(p, "file") ?? "",
                    Str(p, "kind") ?? "",
                    compat.ValueKind == JsonValueKind.Object
                        && compat.TryGetProperty("pluginContract", out var pc)
                        && pc.TryGetInt32(out var pcv) ? pcv : 0,
                    tools,
                    Str(source, "latest"),
                    Str(source, "sha256"),
                    Str(requires, "description"),
                    Str(requires, "install")));
            }

            return entries;
        }
        catch (JsonException) { return null; }
    }

    private static string? Str(JsonElement element, string name) =>
        element.ValueKind == JsonValueKind.Object
        && element.TryGetProperty(name, out var v)
        && v.ValueKind == JsonValueKind.String
            ? v.GetString()
            : null;
}
